name: CI/CD
on:
  push:
    paths:
      - src/**
      - stories/**
      - features/**
      - package.json
      - package-lock.json
      - cucumber.js
      - .github/workflows/CICD.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy via SSH
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.CICDSSH }}"
          mkdir ~/.ssh
          ssh-keyscan speely.net >> ~/.ssh/known_hosts
          scp -r ./src/* github@speely.net:~/home/
